spring:
  application:
    name: APIGATEWAY
  cloud:
    gateway:
      routes:
        - id: RATINGSERVICE
          uri: lb://RATINGSERVICE
          predicates:
            - Path=/rating/**

        - id: HOTELSERVICE
          uri: lb://HOTELSERVICE
          predicates:
            - Path=/hotel/**

        - id: USERSERVICE
          uri: lb://USERSERVICE
          predicates:
            - Path=/users/**
  config:
    import: configserver:http://localhost:8085
server:
  port: 8084
