



spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017
      database: RatingMicroservices
  application:
    name: Rating_Service
  config:
    import: configserver:http://localhost:8085
server:
  port: 8083